#!/bin/sh

# 1. 파라미터 수신
REPOS="$1"
REV="$2"

# 2. svnlook 경로
SVNLOOK=/usr/bin/svnlook
AUTHOR=$($SVNLOOK author -r "$REV" "$REPOS")
LOG_MSG=$($SVNLOOK log -r "$REV" "$REPOS")

# 3. JSON 페이로드 생성
JSON_DATA=$(cat <<EOF
{
  "repo": "$REPOS",
  "revision": "$REV",
  "author": "$AUTHOR",
  "message": "$LOG_MSG"
}
EOF
)

# 4. 리뷰 봇 서버로 전송 (서버 IP/포트를 환경에 맞게 수정 해 주세요.)
curl -X POST http://review-bot:8080/webhook/svn \
     -H "Content-Type: application/json" \
     -d "$JSON_DATA"